docker-compose  -f docker-common.yml up -d --force-recreate
docker-compose  -f docker-company.yml  up  -d --force-recreate
docker-compose  -f docker-coordinatecompany.yml   up  -d --force-recreate
docker-compose  -f docker-menuoperaterole.yml  up  -d --force-recreate
docker-compose  -f docker-user.yml  up  -d --force-recreate
docker-compose  -f docker-dictionary.yml  up  -d --force-recreate
docker-compose  -f docker-file.yml  up  -d --force-recreate
docker-compose  -f docker-id.yml  up  -d --force-recreate
docker-compose  -f docker-project.yml  up  -d --force-recreate
docker-compose  -f docker-team.yml up  -d --force-recreate
docker-compose  -f docker-workcircle.yml  up  -d --force-recreate
docker-compose  -f docker-quartz.yml up  -d --force-recreate
docker-compose  -f docker-activiti.yml up  -d --force-recreate
docker-compose  -f docker-sign.yml up -d --force-recreate
docker-compose  -f docker-interfaceuser.yml up -d --force-recreate
docker-compose  -f docker-cloudplug.yml up -d --force-recreate
docker-compose  -f docker-ireport.yml up -d --force-recreate
docker-compose -f docker-bigscreen.yml up -d --force-recreate