docker-compose  -f docker-common.yml down
docker-compose  -f docker-company.yml  down
docker-compose  -f docker-coordinatecompany.yml   down
docker-compose  -f docker-menuoperaterole.yml  down
docker-compose  -f docker-user.yml  down
docker-compose  -f docker-dictionary.yml  down
docker-compose  -f docker-file.yml  down
docker-compose  -f docker-id.yml  down
docker-compose  -f docker-project.yml  down
docker-compose  -f docker-team.yml down
docker-compose  -f docker-workcircle.yml  down
docker-compose  -f docker-quartz.yml down
docker-compose  -f docker-activiti.yml down
docker-compose  -f docker-sign.yml down
docker-compose  -f docker-interfaceuser.yml down
docker-compose  -f docker-cloudplug.yml down
docker-compose  -f docker-ireport.yml down
docker-compose -f docker-bigscreen.yml down